name: Release Drafter

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ github.token }}

  publish_release:
    needs:
    - release_draft
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v6
      with:
        publish: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
