name: Terraform

on:
  pull_request:

permissions:
  actions: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.0

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -recursive -diff=true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: tfsec
      uses: tfsec/tfsec-pr-commenter-action@main
      with:
        github_token: ${{ github.token }}
